fix(cd): curl script moved into workflow

diff --git a/.github/workflows/docker-test.yml b/.github/workflows/docker-test.yml
--- a/.github/workflows/docker-test.yml
+++ b/.github/workflows/docker-test.yml
@@ -27,9 +27,15 @@ jobs:
         docker run --rm --name farmservice-backend-test --env-file ./.env -p 8000:8000 -d farmservice-backend-test
 
     - name: Test container's response
-      shell: bash
       run: |
-        pwd
-        ls ./tests
-        chmod +x ./tests/reachability_test.sh
-        ./tests/reachability_test.sh
+        URL="http://localhost:8000/api/v1/test"
+        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")
+        if [ $? -ne 0 ]; then
+          echo "Error: Failed to reach $URL" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+        if [[ ! $STATUS_CODE =~ ^2 ]]; then
+          echo "Error: Received HTTP status code $STATUS_CODE" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+        echo "Success: Received HTTP status code $STATUS_CODE" >> $GITHUB_STEP_SUMMARY
